Checking if mysql starts properly

diff --git a/admin/trunk/etc/rc.d/init.d/alien-mysqld b/admin/trunk/etc/rc.d/init.d/alien-mysqld
--- a/admin/trunk/etc/rc.d/init.d/alien-mysqld
+++ b/admin/trunk/etc/rc.d/init.d/alien-mysqld
@@ -61,6 +61,9 @@ start()
 	5.1*)
 	    log="log-error"
 	    ;;
+	5.5*)
+	    log="log-error"
+	    ;;
         *)
 	   log="err-log"
 	  ;;
@@ -112,16 +115,25 @@ stop(){
 
 	homedir=$BASEDIR/$organisation/mysql	
 	echo -n "Killing mysqld of $organisation"
+ 	PID=`cat $homedir/mysqld.pid  2> /dev/null `
+	/bin/kill $PID > /dev/null 2>&1
+    ret=$?
+    if [ $ret -eq 0 ]; then
+        action $"Stopping $prog: " /bin/true
+    else
+        action $"Stopping $prog: " /bin/false
 
-	/bin/kill `cat $homedir/mysqld.pid  2> /dev/null ` > /dev/null 2>&1
-        ret=$?
-        if [ $ret -eq 0 ]; then
-            action $"Stopping $prog: " /bin/true
-        else
-            action $"Stopping $prog: " /bin/false
-
-        fi
-        [ $ret -eq 0 ] && rm -f $homedir/mysql.sock
+    fi
+    [ $ret -eq 0 ] && rm -f $homedir/mysql.sock
+    
+    echo "Checking if the process $PID is still there "
+    while /bin/kill -0 $PID > /dev/null 2>&1 ; do
+    	echo "The process $PID is still there"
+    	sleep 1
+    done
+    
+    
+    
 	if [ -f $homedir/mysqld.pid.monitor ] ;
 	then
 	    PID=`cat $homedir/mysqld.pid.monitor`
